from __future__ import annotations

from typing import Any, Protocol

from goldai.events import Event
from goldai.market import MarketBar, MarketTick
from goldai.strategies import StrategyDecision


class GoldAIStorage(Protocol):
    """Technology-neutral storage contract for M0 and future adapters."""

    def append_ticks(self, ticks: list[MarketTick]) -> None: ...

    def append_bars(self, bars: list[MarketBar]) -> None: ...

    def save_strategy_decision(self, decision: StrategyDecision) -> None: ...

    def save_signal(self, signal: dict[str, Any]) -> None: ...

    def save_position(self, position: dict[str, Any]) -> None: ...

    def save_trade(self, trade: dict[str, Any]) -> None: ...

    def save_trade_outcome(self, outcome: dict[str, Any]) -> None: ...

    def append_event(self, event: Event) -> None: ...

    def save_research_run(self, run: dict[str, Any]) -> None: ...

    def save_strategy_version(self, version: dict[str, Any]) -> None: ...

    def save_daily_report(self, report: dict[str, Any]) -> None: ...

